on:
  push:

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build & Package"
        run: |
          ls -la /usr/bin/xcodebuild*
          # ./package_dmg.sh
