on:
  push:

jobs:
  release:
    runs-on: macos-latest

    permissions:
      contents: write

    steps:
      - name: "Checkout"
        uses: actions/checkout@v4

      - name: "Build & Package"
        run: |
          xcode-select -print-path
          sudo xcode-select -switch /Applications/Xcode_16.2.app	
          xcode-select -print-path

          ./package_dmg.sh
